### ISSUE TITLE
[MNT] CI failing due to missing codecov token

### ISSUE THREAD

**Issue by fkiraly** [felipeangelimvieira/prophetverse#40]
The CI seems to be failing due to a missing codecov token?

Example: https://github.com/felipeangelimvieira/prophetverse/actions/runs/9032395207/job/24820502043?pr=22

**Comment by felipeangelimvieira** [comment]
That's strange, it happens only with dependabot PRs 🤔 
[The CI execution of this PR](https://github.com/felipeangelimvieira/prophetverse/actions/runs/9120662978/job/25078435330?pr=46) that I've just opened worked well... Maybe it has to do with permission to access the token, depending on who's lauching the CI process?
I'll take a loot at it later. Thank you for pointing this out Franz

**Comment by felipeangelimvieira** [comment]
Seems to have solved dependabot CI workflows by adding secrets to the project settings. The codecov secret was missing in "Dependabot" section.

https://github.com/felipeangelimvieira/prophetverse/actions/runs/9417860637
