### ISSUE TITLE
[MNT] Update skbase to run sktime's contract validation tests

### ISSUE THREAD

**Issue by felipeangelimvieira** [felipeangelimvieira/prophetverse#47]
As discussed with @fkiraly, the previous version of skbase wasn't properly validating jax.numpy attributes (see sktime/skbase#324)

The tests are now being skipped, but can be properly executed with this update.

**Comment by felipeangelimvieira** [comment]
Yes! It's working with #323. This week I expect to create a PR with some changes in code and without skipping the sktime contract tests. The tests passed in my local machine.

**Comment by felipeangelimvieira** [comment]
The test is creating some problems in the CI workflow... it seems to be a common issue with github actions (actions/runner-images#6680), and it may be related to CPU / memory usage. Have you ever experienced it in sktime, @fkiraly ?

[Example of CI failure](https://github.com/felipeangelimvieira/prophetverse/actions/runs/9436392088/job/25991042834)

**Comment by fkiraly** [comment]
Yes, and we have not fully diagnosed it.

Our suspicion is that this happens for memory intensive models, and the approach is selecting test parameters in `get_test_params` that lead to low memory and runtime requirements.

**Comment by fkiraly** [comment]
Plus, it seems that `test_sktime_contract` is being skipped, so the failure is coming from the other tests.

**Comment by felipeangelimvieira** [comment]
> Plus, it seems that `test_sktime_contract` is being skipped, so the failure is coming from the other tests.

Locally, the tests are being executed partially but then skipped manually by a particular test case:

Output of `pytest tests/sktime/test_sktime_check_estimator.py -vvrs`


```
================================================================== short test summary info ===================================================================
SKIPPED [4] .venv/lib/python3.11/site-packages/sktime/forecasting/tests/test_all_forecasters.py:215: ForecastingHorizon with timedelta values is currently experimental and not supported everywhere
======================================================= 4 skipped, 1930 warnings in 619.14s (0:10:19) ========================================================
```

**Comment by fkiraly** [comment]
Should be addressed and explained by https://github.com/sktime/sktime/pull/6587 - let's wait with closing this until the release though.
